booksproject/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.contrib import admin
from booksproject import views, settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

# from accounts.forms import CustomAuthForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.IndexTemplateView.as_view(), name ='index'),

    # Book and Albums
    path('books/',include('books.urls', namespace='books')),
    path('api_books/',include('books.api.urls', namespace = 'api_books')),
    path('albums/',include('albums.urls', namespace='albums')),
    path('api_albums/',include('albums.api.urls', namespace = 'api_albums')),
    
    # TAGR App
    path('tagr/',include('tagr.urls', namespace='tagr')),
    
    path('profile/',include('profile.urls', namespace='profile')),

    # path('contact/', views.contactform, name='contactform'),
    path('about_contact/', views.about_contact, name='about_contact'),
    path('thankyou/', views.ThankYou.as_view(), name='thankyou'),
    
    path('apiinfo/', views.APIInfoTemplateView.as_view(), name='apiinfo'),

    # Foods Apps
    path('foods/', include('foods.urls',namespace = 'foods')),
    path('expenses/', include('expenses.urls',namespace = 'expenses')),
    path('exercises/', include('exercises.urls',namespace = 'exercises')),
    path('reports/', include('reports.urls',namespace = 'reports')),

    # path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=CustomAuthForm, redirect_authenticated_user=True), name = 'user_login'),
    # path('logout/', auth_views.LogoutView.as_view(), name = 'user_logout'),
    
    # path('change-password/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('user_logout')), name='password_change'),
    # path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z](1, 13)-[0-9A-Za-z](1, 20))/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tagr/api/urls.py
from django.conf.urls import url
from tagr.api import views
app_name = 'api_tagr'
urlpatterns = [
	url(r'(?P<pk>\d+)',views.PostRUDAPIView.as_view(),name='api_blog'),
]

tagr/urls.py
from django.conf.urls import url
from tagr import views


app_name='tagr'

urlpatterns=[
	url(r'^$',views.IndexTemplateView.as_view(), name = 'index'),
	url(r'^questions/$',views.PostListView.as_view(), name = 'post_list'),
	url(r'^(?P<chapter>\d+)/(?P<pk>\d+)/$',views.PostDetailView.as_view(), name = 'post_detail'),
	url(r'^update/(?P<chapter>\d+)/(?P<pk>\d+)/$',views.PostUpdateView.as_view(), name = 'post_update'),
]

tagr/api/models.py
from rest_framework import serializers
from tagr.models import Post

class PostSerializer(serializers.ModelSerializer):
	class Meta():
		model = Post

tagr/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.shortcuts import reverse
import datetime
from django.contrib.auth import get_user_model

from django.dispatch import receiver
from django.db.models.signals import post_save

User = get_user_model()

def add_one():
    '''
    Returns the next default value for the `ones` field, starts with 
    500
    '''
    if User.is_authenticated:
	    largest = Post.objects.filter(user=user).order_by('ones').last().ones
	    if not largest:
	        return 0
	    return largest + 1

# Create your models here.
class Post(models.Model):
	user = models.ForeignKey(User, related_name = 'postuser', null=True, blank=True, on_delete=models.CASCADE)
	question = models.CharField(max_length = 255)
	chapter = models.IntegerField()
	message = models.TextField(null=True, blank=True)
	create_date = models.DateField(default = datetime.date.today)
	publish_status = models.BooleanField(default=False)
	question_number = models.IntegerField(null=True)

	def __str__(self):
		return self.question

	def get_absolute_url(self):
		return reverse('tagr:post_detail',kwargs={'pk':self.pk, 'chapter':self.chapter})

	def publish_question(self):
		self.publish_question = True
		self.save()

	def next(self):
		try:
			return Post.objects.get(pk=self.pk+1)
		except:
			return None

	def previous(self):
		try:
			return Post.objects.get(pk=self.pk-1)
		except:
			return None


@receiver(post_save, sender=User)
def ensure_profile_exists(sender, **kwargs):
	if kwargs.get('created', False):
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 1,question_number=1, question='What is the most helpful idea from this chapter for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 1,question_number=2, question='How does the story of Edwin C. Barnes inspire you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 1,question_number=3, question='When have you stopped "three feet from gold" in your life?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 1,question_number=4, question='Can you think of examples when a "temporary defeat" turned into a victory in your life?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 1,question_number=5, question='Are you willing to stake everything to move toward your burning desire?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 1,question_number=6, question='Would you categorize yourself as being "success conscious" or "failure conscious" up until now?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 1,question_number=7, question='What does the phrase "I am the Master of my Fate,  I am the Captain of my Soul" mean to you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 2,question_number=8, question='What is the most helpful idea from this chapter for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 2,question_number=9, question='How does the story of the burning ships apply to you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 2,question_number=10, question='Have you found your "Statement of Desire"?  If not,  please do so and record it below?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 2,question_number=11, question='Does your "Statement of Desire" accurately reflect your burning desire?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 2,question_number=12, question='The turning point in the lives of those who succeed usually comes at the moment of some crisis,  through which they are introduced to their other selves.  What is the turning point in your life?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 2,question_number=13, question='What does Napoleon Hill mean when he refers to the "their" ‘other selves’?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 2,question_number=14, question='What is the difference between "wishing for a thing" and "being ready to "receive it"?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 2,question_number=15, question='Are you truly ready to receive what you desire?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 3,question_number=16, question='What is the most helpful idea from this chapter for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 3,question_number=17, question='How does Napoleon Hill define "faith"?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 3,question_number=18, question='How can you develop more Faith?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 3,question_number=19, question='What are affirmations?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 3,question_number=20, question='How can memorizing the "Self-Confidence Formula" positively affect your life?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 3,question_number=21, question='Both poverty and riches are the offspring of thought.  How has this been true for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 4,question_number=22, question='What is the most helpful idea from this chapter for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 4,question_number=23, question='How does Napoleon Hill define Auto-Suggestion?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 4,question_number=24, question='How much control do you have over the material that reaches your mind?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 4,question_number=25, question='How diligent are you in protecting the "garden of your mind" from negative thoughts?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 4,question_number=26, question='What do you need to add to the words (auto-suggestion) to make your subconscious mind recognize and act upon them?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 4,question_number=27, question='Be on the alert of the plans that your subconscious mind will have over to you and when they appear,  put them into action immediately.  What is an example of taking action immediately on a plan or an idea that has come into your mind?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 4,question_number=28, question='What will happen if you follow some of the instruction of auto-suggestion but not others?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 4,question_number=29, question='How can you become the master of yourself and your environment?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 5,question_number=30, question='What is the most helpful idea from this chapter for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 5,question_number=31, question='What kinds of specialized knowledge do you have? What kinds of specialized knowledge would help you go to another level?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 5,question_number=32, question='How many kinds of specialized knowledge can you think of beyond those taught in school?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 5,question_number=33, question='How can a Master Mind Group contribute to your specialized knowledge?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 5,question_number=34, question='Those who are not successful usually make the mistake of believing that the knowledge acquiring period ends when one finishes school.  How have you continued to acquire specialized knowledge?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 5,question_number=35, question='Doing a thing well never is trouble!  Do you strive to do everything you do as well as you can?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 5,question_number=36, question='Both success and failure are largely the result of what?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 6,question_number=37, question='What is the most helpful idea from this chapter for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 6,question_number=38, question='What are the two forms of imagination and how are they unique?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 6,question_number=39, question='What form of imagination will you use to create your goal?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 6,question_number=40, question='What is the beginning point in all fortunes?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 6,question_number=41, question='Success requires no explanation,  failure permits no alibis.  How can that statement inspire you in your life?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 7,question_number=42, question='What is the most helpful idea from this chapter for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 7,question_number=43, question='What is the Master Mind and why is forming one important?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 7,question_number=44, question='How have you experienced "temporary defeat" in your life?  How have you overcome it?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 7,question_number=45, question='The Major Attributes of Leadership: Which attributes comes naturally to you?  Which attributes are challenging for you?')
		Post.objects.get_or_create(user=kwargs.get('instance'), chapter = 7,question_number=46, question='The Ten Major Causes of Failure in Leadership: Which of these causes can you identify with?')

tagr/forms.py
from django import forms

from tagr.models import Post

class PostForm(forms.ModelForm):
	class Meta():
		model = Post
		fields = ['question','message','create_date']
		labels = {
			'message': 'Name',
		}

class PostUpdateForm(forms.ModelForm):
	class Meta():
		model = Post
		fields = ['message']
		labels = {
			'message': '',
		}
		widgets = {
			'message': forms.Textarea(
                attrs={'placeholder': 'Enter answer here'}),
		}

tagr/api/views.py
from rest_framework import generics
from tagr.api.models import PostSerializer
from tagr.models import Post

class PostRUDAPIView(generics.RetrieveUpdateDestroyAPIView):
	lookup ='pk'
	serializer_class = PostSerializer
	queryset = Post.objects.all()

tagr/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, reverse

# Create your views here.
from django.views.generic import (TemplateView, ListView, DetailView,
									CreateView, UpdateView, DeleteView)


from tagr.models import Post
from tagr.forms import PostUpdateForm

# from django.core.urlresolvers import reverse_lazy
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

class IndexTemplateView(TemplateView):
	template_name='tagr/index.html'

class PostListView(LoginRequiredMixin, ListView):
	model = Post
	login_url = 'accounts:user_login'

	def get_queryset(self):
		user = self.request.user
		queryset = Post.objects.filter(user=user)
		return queryset

class PostDetailView(LoginRequiredMixin, DetailView):
	model = Post
	login_url = 'accounts:user_login'

	def get_queryset(self):
		user = self.request.user
		queryset = Post.objects.filter(user=user)
		return queryset


class PostUpdateView(LoginRequiredMixin, UpdateView):
	model = Post
	form_class = PostUpdateForm

	def get_queryset(self):
		base_qs = super(PostUpdateView, self).get_queryset()
		return base_qs.filter(user=self.request.user)

@login_required
def post_publish(self, pk):
	post = get_object_or_404(Post, pk = pk)
	post.publish_post()
	return reverse('tagr:post_detail', kwargs={'pk':post.pk})

tagr/templates/tagr/base.html
{% extends 'base.html' %}
{% block content %}
<h1>App Base HTML</h1>
{% endblock %}

tagr/templates/tagr/index.html
{% extends 'tagr/base.html' %}
{% block content %}
<section id='tagr' class='container w-auto pb-3'>
	<h1 class='font-weight-bold pb-2 pt-5'>Welcome to the Think and Grow Rich Challenge</h1>

	<p class='p-2'>Napoeloen Hill set out on a quest to understand the minds of the most Successful people in America.</p>
	<p class='p-2'>Through his journey he discovered some very similar traits in all these people</p>
	<p class='p-2 font-weight-bold'>I propose a challenge to you</p>
	<ul class='list-inline'>
		<li class='h5 list-inline-item pl-3 pr-3'>Read the book</li>
		<li class='h5 list-inline-item pl-3 pr-3'>Answer the questions</li>
	</ul>
	<div class='grid-3'>
		<p class='text-muted text-left'>All answers are private and belong to you</p>
		<p class='text-muted text-center'>All the progress is private and belongs to you</p>
		<p class='text-muted text-right'>All the benefits gained are  private and belong to you</p>
	</div>
	<hr>
	<div class='tagr_schedule'>
		<h4 class='text-left'>The Schedule</h4>
		<h5 class='text-left'>15 Weeks...Starting Now</h5>
		<p class='text-left'>Read 1 Chapter, only 1 Chapter per week and document your thoughts...that's it</p>
	</div>
	<hr>
	
	<div class="grid-5">
		<a class='btn btn-info w-100' href="{% url 'account_signup' %}">Sign Up</a>
		<i class="fas fa-angle-double-left text-info fa-2x"></i>
		<p>Do you have an Account?</p>
		<i class="fas fa-angle-double-right text-dark fa-2x"></i> 
		<a class='btn btn-dark w-100' href="{% url 'account_login' %}?next={% url 'tagr:post_list' %}">Login</a>
	</div>
	
</section>



{% endblock %}

tagr/templates/tagr/post_confirm_delete.html
{% extends 'tagr/base.html' %}
{% block content %}
<h1>tagr HTML</h1>



{% endblock %}

tagr/templates/tagr/post_detail.html
{% extends 'tagr/base.html' %}
{% block content %}
<section id='question'>
	<h1 class='sectionTitle'>Chapter {{post.chapter}}</h1 >

	<div class="card mb-3">
		<div class="card-header">
		{{post.question_number}}. {{post.question}}
		</div>
		<div class="card-body pb-2">
			<p class="card-text text-left pb-5">{{post.message}}</p>
			<p class="card-text">{{post.create_date}}</p>
		</div>
	</div>

	<div class="grid-3 p-3">
		{% if post.previous %}
		<a class='btn btn-info' href="{% url 'tagr:post_detail' pk=post.previous.pk chapter=post.chapter %}">Previous Question</a>
		{% else %}
		<div><p class="btn btn-outline-secondary text-muted w-100">First Question</p></div>
		{% endif %}
		<a class='btn btn-success' href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">Update</a>
		
		{% if post.next %}
		<a class='btn btn-primary' href="{% url 'tagr:post_detail' pk=post.next.pk chapter=post.chapter%}">Next Question</a>
		{% endif %}
	</div>
</section>		
{% endblock %}

{% block aftercontent %}
	<div class='pt-4'>
		<a class="btn btn-warning" href="{% url 'tagr:post_list' %}">Back to Questions</a>
	</div>
{% endblock %}

tagr/templates/tagr/post_form.html
{% extends 'tagr/base.html' %}
{% block content %}
<section id='question_update'>
	<h1 class='sectionTitle'>Chapter {{post.chapter}}</h1>
	<p class='lead'>{{post.question}}</p>
	<form method="POST" class='tagrQuestion'>
		{% csrf_token %}
		{{form.as_p}}
		<input class='btn btn-block btn-info' type="submit" value="Save">
	</form>
</section>

{% endblock %}

tagr/templates/tagr/post_list.html
{% extends 'tagr/base.html' %}
{% load static %}
{% block content %}

<section id='tagr_list'>
	
	<h1 class='sectionTitle'>Think and Grow Rich Challenge</h1>
	<div class='grid-3 text-muted pb-3'>
		<p>Read each Chapter</p>
		<p>Reflect on what you read</p>
		<p>Journal your thoughts</p>
	</div>
	<p class='pt-3 pb-4' ><a class='btn btn-info btn-lg' href="{% static 'img/Think-And-Grow-Rich_2008.pdf' %}">Get the book!</a></p>

	<table class="table table-striped table-dark text-left">
		<thead>
			<th width='20%'>Chapter</th>
			<th width="80%">Questions</th>
		</thead>
		<tbody>
			<tr>
				<td>Chapter 1</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 1 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 2</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 2 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 3</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 3 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 4</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 4 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 5</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 5 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 6</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 6 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 7</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 7 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 8</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 8 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 9</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 9 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 10</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 10 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 11</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 11 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 12</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 12 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 13</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 13 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 14</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 14 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
			<tr>
				<td>Chapter 15</td>
				<td>
				{% for post in post_list %}	
					{% if post.chapter == 15 %}
						<p class='p-2'><a href="{% url 'tagr:post_update' pk=post.pk chapter=post.chapter %}">{{post.question}}</a>
						{% if post.message %}
						<div class='postmessage'>
							<p>{{post.message}}</p><br>
							<p>Last Updated: {{post.create_date}}</p>
						</div>
						{% endif %}
					{% endif %}
				{% endfor %}
				</td>
			</tr>
		</tbody>
	</table>

</section>	
{% endblock %}