booksproject/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.contrib import admin
from booksproject import views, settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

# from accounts.forms import CustomAuthForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.IndexTemplateView.as_view(), name ='index'),

    # Book and Albums
    path('books/',include('books.urls', namespace='books')),
    path('api_books/',include('books.api.urls', namespace = 'api_books')),
    path('albums/',include('albums.urls', namespace='albums')),
    path('api_albums/',include('albums.api.urls', namespace = 'api_albums')),
    
    # TAGR App
    path('tagr/',include('tagr.urls', namespace='tagr')),
    
    path('profile/',include('profile.urls', namespace='profile')),

    # path('contact/', views.contactform, name='contactform'),
    path('about_contact/', views.about_contact, name='about_contact'),
    path('thankyou/', views.ThankYou.as_view(), name='thankyou'),
    
    path('apiinfo/', views.APIInfoTemplateView.as_view(), name='apiinfo'),

    # Foods Apps
    path('foods/', include('foods.urls',namespace = 'foods')),
    path('expenses/', include('expenses.urls',namespace = 'expenses')),
    path('exercises/', include('exercises.urls',namespace = 'exercises')),
    path('reports/', include('reports.urls',namespace = 'reports')),

    # path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=CustomAuthForm, redirect_authenticated_user=True), name = 'user_login'),
    # path('logout/', auth_views.LogoutView.as_view(), name = 'user_logout'),
    
    # path('change-password/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('user_logout')), name='password_change'),
    # path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z](1, 13)-[0-9A-Za-z](1, 20))/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/api/urls.py
from django.conf.urls import url
from accounts.api import views
app_name = 'api_accounts'
urlpatterns = [
	url(r'(?P<pk>\d+)',views.UserModelRUDAPIView.as_view(),name='api_accounts'),
]

profile/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from profile import views
from django.contrib.auth import views as auth_views
# from django.core.urlresolvers import reverse_lazy
from django.urls import reverse_lazy
from profile.forms import CustomAuthForm

app_name='profile'

urlpatterns=[
	path('',views.ProfileListView.as_view(), name = 'index'),
	re_path('invite_trainer/(?P<pk>\d+)',views.invite_trainer, name = 'invite_trainer'),
	# re_path(r'^signup/$',views.signup, name = 'signup'),

	re_path('detail/(?P<pk>\d+)',views.ProfileDetailView.as_view(), name = 'profile_detail'),
	# path('create/',views.ProfileCreateView.as_view(), name = 'profile_create'),
	re_path('update/(?P<pk>\d+)/',views.ProfileUpdateView.as_view(), name = 'profile_update'),
	re_path('delete/(?P<pk>\d+)/',views.ProfileDeleteView.as_view(), name = 'profile_delete'),	
]

tagr/urls.py
from django.conf.urls import url
from tagr import views


app_name='tagr'

urlpatterns=[
	url(r'^$',views.IndexTemplateView.as_view(), name = 'index'),
	url(r'^questions/$',views.PostListView.as_view(), name = 'post_list'),
	url(r'^(?P<chapter>\d+)/(?P<pk>\d+)/$',views.PostDetailView.as_view(), name = 'post_detail'),
	url(r'^update/(?P<chapter>\d+)/(?P<pk>\d+)/$',views.PostUpdateView.as_view(), name = 'post_update'),
]

profile/api/models.py
from rest_framework import serializers
from accounts.models import UserModel

class UserModelSerializer(serializers.ModelSerializer):
	class Meta():
		model = UserModel

profile/models.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals
from django.shortcuts import reverse
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save

User = get_user_model()

class Profile(models.Model):
	user = models.OneToOneField(User, related_name='user_profile', on_delete=models.SET_DEFAULT, primary_key=True, default=1)
	ideal_fat = models.IntegerField(default=20)
	ideal_protein = models.IntegerField(default=40)
	ideal_carbs = models.IntegerField(default=40)
	ideal_weight = models.IntegerField(default=185)
	ideal_calories = models.IntegerField(default=2000)
	current_weight = models.IntegerField(default=185)
	trainer_email = models.EmailField(null=True, blank=True)


	def __str__(self):
		return self.user.username

	def get_absolute_url(self):
		return reverse('profile:profile_detail', kwargs={'pk':self.pk})


def post_add_trainer_email(sender, instance, *args, **kwargs):
	if not instance.trainer_email:
		instance.trainer_email = instance.user.email

post_save.connect(post_add_trainer_email, sender=Profile)

profile/forms.py
from django import forms
from profile.models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from allauth.account.forms import SignupForm

# class UserForm(UserCreationForm):
# 	class Meta():
# 		model = Profile
# 		fields = ['email','password1','password2',
# 				'ideal_carbs','ideal_protein','ideal_fat','ideal_weight','ideal_calories','current_weight']

class ProfileForm(SignupForm):
    class Meta:
        model = Profile

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['ideal_carbs'] = forms.CharField(required=True, initial=40)
        self.fields['ideal_carbs'].label = 'Carbohydrates Per Day in %'
        
        self.fields['ideal_protein'] = forms.CharField(required=True, initial=40)
        self.fields['ideal_protein'].label = 'Protein Per Day in %'

        self.fields['ideal_fat'] = forms.CharField(required=True, initial=20)
        self.fields['ideal_fat'].label = 'Fat Per Day in %'

        self.fields['ideal_calories'] = forms.CharField(required=True, initial=2000)
        self.fields['ideal_calories'].label = 'Target Daily Caloric Intake (Suggested, Women: 1500, Men: 2000)'

        self.fields['ideal_weight'] = forms.CharField(required=True, initial=185)
        self.fields['ideal_weight'].label = "What is your Target/Goal Weight"
        
        self.fields['current_weight'] = forms.CharField(required=True, initial=200)
        self.fields['current_weight'].label = "Current Weight"

        self.fields['trainer_email'] = forms.EmailField(required=False)
        self.fields['trainer_email'].label = 'If you already have a trainer, Invite them to see your activity'

    def save(self, request):
        user = super(ProfileForm, self).save(request)
        user.ideal_carbs = self.cleaned_data.pop('ideal_carbs')
        user.ideal_protein = self.cleaned_data.pop('ideal_protein')
        user.ideal_fat = self.cleaned_data.pop('ideal_fat')
        user.ideal_weight = self.cleaned_data.pop('ideal_weight')
        user.ideal_calories = self.cleaned_data.pop('ideal_calories')
        user.current_weight = self.cleaned_data.pop('current_weight')
        user.trainer_email = self.cleaned_data.pop('trainer_email')
        Profile.objects.get_or_create(user_id=user.id,
            ideal_calories=user.ideal_calories,
            ideal_carbs=user.ideal_carbs,
            ideal_fat=user.ideal_fat,
            ideal_weight=user.ideal_weight,
            ideal_protein=user.ideal_protein,
            current_weight=user.current_weight,
            trainer_email=user.email)
        return user


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['current_weight','ideal_weight','ideal_calories','ideal_carbs','ideal_protein','ideal_fat']
        labels = {
            'ideal_carbs':'Carbohydrates Per Day in %',
            'ideal_protein':'Protein Per Day in %',
            'ideal_fat':'Fat Per Day in %',
            'ideal_calories':'Target Daily Caloric Intake (Suggested, Women: 1500, Men: 2000)',
            'ideal_weight':"What is your Target/Goal Weight",
            'current_weight':"Current Weight",
            'trainer_email':'If you already have a trainer, Invite them to see your activity',
        }

    def clean(self):
        cleaned_data = super().clean()
        # print(cleaned_data['ideal_fat'])
        # print(cleaned_data)
        # print(self)
        # # print(dir(self))
        if (cleaned_data['ideal_fat'] + cleaned_data['ideal_protein'] + cleaned_data['ideal_carbs']) != 100: 
            msg = "Carbs Fats and Protein Percentages must add up to 100"
            self.add_error('ideal_fat', msg)
            self.add_error('ideal_protein', msg)
            self.add_error('ideal_carbs', msg)
               
         


class InviteTrainerForm(forms.ModelForm):
	class Meta():
		model = Profile
		fields = ['trainer_email']

class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class':'validate','placeholder': 'Enter Your Email Address'}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Enter Your Password'}))

profile/api/views.py
from rest_framework import generics
from accounts.api.models import UserModelSerializer
from accounts.models import UserModel

class UserModelRUDAPIView(generics.RetrieveUpdateDestroyAPIView):
	lookup ='pk'
	serializer_class = UserModelSerializer
	queryset = UserModel.objects.all()

profile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
# from django.core.urlresolvers import reverse_lazy
from django.urls import reverse_lazy

# Create your views here.
from django.http import HttpResponse
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from profile.models import Profile
from profile.forms import ProfileForm, ProfileUpdateForm, InviteTrainerForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from foods.models import Food
from django.contrib.auth import get_user_model

User = get_user_model()

class IndexTemplateView(TemplateView):
	template_name='profile/index.html'


class ProfileListView(LoginRequiredMixin, ListView):
	model = Profile
	# template_name = 'profile/profile_list.html'
	# context_object_name = 'user_list'
	def get_queryset(self):
		user = self.request.user
		queryset = Profile.objects.filter(user=user)
		return queryset

class ProfileDetailView(LoginRequiredMixin, DetailView):
	model = Profile
	template_name = 'profile/profile_detail.html'
	
	# def get_context_data(self, **kwargs):
	# 	context = super(ProfileDetailView, self).get_context_data(**kwargs)
	# 	context['trainees'] = Profile.objects.filter(trainer_email=self.request.user)
	# 	foods = dict()
	# 	for index,trainee in enumerate(context['trainees']):
	# 		foods[index] = Food.objects.filter(user_id=trainee.pk)
	# 	context['foods'] = foods
	# 	context['range'] = str(len(context['trainees']) + 10)
	# 	return context

	def get_queryset(self):
		user = self.request.user
		queryset = Profile.objects.filter(user=user)
		return queryset

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
	model = Profile
	form_class = ProfileUpdateForm

class ProfileDeleteView(LoginRequiredMixin, DeleteView):
	model = Profile
	success_url = reverse_lazy('index')

@login_required
def invite_trainer(request, pk):
	if request.method == 'POST':
		form = InviteTrainerForm(request.POST, instance=request.user)
		if form.is_valid():
			profile = form.save(commit=False)
			profile.save()
			return redirect('profile:user_detail', pk=pk)
		else:
			return HttpResponse(forms.errors)
	else:
		form = InviteTrainerForm(instance = request.user)
	return render(request, 'profile/invite_trainer_form.html', {'form':form})



# @login_required
# def update(request, pk):
# 	if request.method == 'POST':
# 		form = ProfileUpdateForm(request.POST, instance=request.user)
# 		if form.is_valid():
# 			profile = form.save(commit=False)
# 			profile.username = profile.email
# 			profile.save()
# 			return redirect('profile:user_detail', pk=pk)
# 	else:

# 		form = ProfileUpdateForm(instance=request.user)
# 	return render(request, 'profile/signup.html', {'form': form})

profile/templates/profile/base.html
{% extends 'base.html' %}
{% block content %}
<h1>App Base HTML</h1>
{% endblock %}

profile/templates/profile/index.html
{% extends 'profile/base.html' %}
{% block content %}
<h1>Profile HTML</h1>
{% endblock %}

profile/templates/profile/invite_trainer_form.html
{% extends 'profile/base.html' %}
{% block content %}

<h1>Invite Trainer</h1>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<input class='update_button' type="submit" value="Update">
</form>
{% endblock %}

profile/templates/profile/login.html
{% extends 'profile/base.html' %}
{% block content %}
<section id='login' class='container w-auto pb-3'>
<h1 class='font-weight-bold pb-2 pt-5'>Login</h1>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<input class='btn btn-block btn-info' type="submit" value="Login">
	<p class='signup'>Don't have an Account...Go ahead and <a href="{% url 'accounts:signup' %}">SignUp</a></p>
	<h3 class='forgot'><a href="{% url 'password_reset' %}">Forgot?</a></h3>
</form>
<div class='nopass'>
	
</div>
<div class='clr'></div>
</section>
{% endblock %}

profile/templates/profile/profile_detail.html
{% extends 'profile/base.html' %}
{% block content %}
<section id='profile_detail'>
<h1 class='sectionTitle'>Profile Detail</h1>
<td>{{profile.email}}</td>
<table class="table table-striped">
		<thead>
			<th>Current Weight</th>
			<th>Goal Weight</th>
			<th>Desired Calories</th>
			<th>Total Carbs</th>
			<th>Total Protein</th>
			<th>Total Fat</th>
		</thead>
		<tr>
			<td>{{profile.current_weight}}</td>
			<td>{{profile.ideal_weight}}</td>
			<td>{{profile.ideal_calories}}</td>
			<td>{{profile.ideal_carbs}}</td>
			<td>{{profile.ideal_protein}}</td>
			<td>{{profile.ideal_fat}}</td>
		</tr>
	</table>
	<div class="grid-2">
		<a class='btn btn-info' href="{% url 'profile:profile_update' pk=profile.pk %}">Update</a>
		<a class='btn btn-primary' href="{% url 'profile:profile_delete' pk=profile.pk %}">Delete</a>
	</div>
</section>
{% endblock %}

profile/templates/profile/profile_form.html
{% extends 'profile/base.html' %}

{% block content %}
<h1 class='sectionTitle'>Update Details</h1>
<form method='POST' class="profileUpdateForm">
	{% csrf_token %}
	{{form}}
	<input class='btn btn-info btn-block' type="submit" value='Submit'>
</form>
{% endblock %}

profile/templates/profile/profile_list.html
{% extends 'profile/base.html' %}
{% block content %}

<h1>Trainers and Trainees</h1>

{% for profile in profile_list %}
	<a href="{% url 'profile:profile_detail' pk=profile.pk %}">
	<p>{{profile.pk}} {{profile.id}}</p>
	<p>Weight {{profile.ideal_weight}}</p>
	<p>carbs {{profile.ideal_carbs}}</p>
	<p>calories {{profile.ideal_calories}}</p>
	<p>fat {{profile.ideal_fat}}</p>
	<p>protein {{profile.ideal_protein}}</p>
	<p>Current Weight {{profile.current_weight}}</p></a>
{% endfor %}
<p>Trainer {{profile.trainer}}</p>
<p>Trainee {{profile.trainee}}</p>
{% endblock %}

profile/templates/profile/signup.html
{% extends 'profile/base.html' %}
{% block content %}
<div class="container pb-3">
	<h1 class='font-weight-bold pt-5'>Signup</h1>
	<form class='signUpForm' method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input class='btn btn-block btn-info' type="submit" value="Sign Up">
	</form>
</div>

{% endblock %}

profile/templates/profile/thankyou.html
{% extends 'profile/base.html' %}
{% block content %}
<h1>Login HTML</h1>

	<p>You Email {{user.email}}</p>
	<p>Password {{user.password}}</p>
	<p>Username {{user.user}}</p>


<a href="{% url 'account_login' %}">Login</a>
{% endblock %}