booksproject/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.contrib import admin
from booksproject import views, settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

# from accounts.forms import CustomAuthForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.IndexTemplateView.as_view(), name ='index'),

    # Book and Albums
    path('books/',include('books.urls', namespace='books')),
    path('api_books/',include('books.api.urls', namespace = 'api_books')),
    path('albums/',include('albums.urls', namespace='albums')),
    path('api_albums/',include('albums.api.urls', namespace = 'api_albums')),
    
    # TAGR App
    path('tagr/',include('tagr.urls', namespace='tagr')),
    
    path('profile/',include('profile.urls', namespace='profile')),

    # path('contact/', views.contactform, name='contactform'),
    path('about_contact/', views.about_contact, name='about_contact'),
    path('thankyou/', views.ThankYou.as_view(), name='thankyou'),
    
    path('apiinfo/', views.APIInfoTemplateView.as_view(), name='apiinfo'),

    # Foods Apps
    path('foods/', include('foods.urls',namespace = 'foods')),
    path('expenses/', include('expenses.urls',namespace = 'expenses')),
    path('exercises/', include('exercises.urls',namespace = 'exercises')),
    path('reports/', include('reports.urls',namespace = 'reports')),

    # path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=CustomAuthForm, redirect_authenticated_user=True), name = 'user_login'),
    # path('logout/', auth_views.LogoutView.as_view(), name = 'user_logout'),
    
    # path('change-password/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('user_logout')), name='password_change'),
    # path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z](1, 13)-[0-9A-Za-z](1, 20))/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exercises/urls.py
from django.urls import path, re_path
from exercises import views


app_name='exercises'

urlpatterns=[
	path('',views.ExerciseListView.as_view(), name = 'exercise_list'),
	re_path('(?P<pk>\d+)/',views.ExerciseDetailView.as_view(), name = 'exercise_detail'),
	path('create/',views.ExerciseCreateView.as_view(), name = 'exercise_create'),
	re_path('update/(?P<pk>\d+)/',views.ExerciseUpdateView.as_view(), name = 'exercise_update'),
	re_path('delete/(?P<pk>\d+)/',views.ExerciseDeleteView.as_view(), name = 'exercise_delete'),

	# List Detail Create Update Delete

]

expenses/urls.py
from django.urls import path, re_path
from expenses import views


app_name='expenses'

urlpatterns=[
	path('',views.ExpenseListView.as_view(), name = 'index'),
	re_path('detail/(?P<pk>\d+)',views.ExpenseDetailView.as_view(), name = 'expense_detail'),
	path('create/',views.ExpenseCreateView.as_view(), name = 'expense_create'),
	re_path('update/(?P<pk>\d+)/',views.ExpenseUpdateView.as_view(), name = 'expense_update'),
	re_path('delete/(?P<pk>\d+)/',views.ExpenseDeleteView.as_view(), name = 'expense_delete'),
]

foods/urls.py
from django.urls import path, re_path
from foods import views


app_name='foods'

urlpatterns=[
	path('',views.FoodListView.as_view(), name = 'food_list'),
	re_path('detail/(?P<pk>\d+)',views.FoodDetailView.as_view(), name = 'food_detail'),
	path('create/',views.FoodCreateView.as_view(), name = 'food_create'),
	re_path('update/(?P<pk>\d+)/',views.FoodUpdateView.as_view(), name = 'food_update'),
	re_path('delete/(?P<pk>\d+)/',views.FoodDeleteView.as_view(), name = 'food_delete'),	
]

reports/urls.py
from django.urls import path, re_path
from reports import views

app_name='reports'

urlpatterns=[
	path('', views.report_list, name='index'),

]

tagr/urls.py
from django.conf.urls import url
from tagr import views


app_name='tagr'

urlpatterns=[
	url(r'^$',views.IndexTemplateView.as_view(), name = 'index'),
	url(r'^questions/$',views.PostListView.as_view(), name = 'post_list'),
	url(r'^(?P<chapter>\d+)/(?P<pk>\d+)/$',views.PostDetailView.as_view(), name = 'post_detail'),
	url(r'^update/(?P<chapter>\d+)/(?P<pk>\d+)/$',views.PostUpdateView.as_view(), name = 'post_update'),
]

reports/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

reports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, reverse
from django.views.generic import (TemplateView, ListView, DetailView, CreateView,
									UpdateView, DeleteView)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from profile.models import Profile
from foods.models import Food
from expenses.models import Expense
from exercises.models import Exercise
from foods.forms import FoodForm
from expenses.forms import ExpenseForm
from exercises.forms import ExerciseForm
from django.http import HttpResponse
import datetime
from django.contrib.auth import get_user_model

User = get_user_model()


# print(today, seven_days_ago)


# Calories/Dollars, Offset from Goal, Exercise Deficit
def cal_offset_func(accounts, foods, expenses, exercises, days):
	
	actual_calories = actual_expenses = actual_fat = actual_carbs = actual_protein = actual_servings = total_expenses = total_burned = 0.0

	for food in foods:
		actual_servings = food.servings
		if actual_servings > 1:
			actual_calories += food.calories * food.servings
			actual_fat += food.fat * food.servings
			actual_carbs += food.carbs * food.servings
			actual_protein += food.protein * food.servings
		else:
			actual_calories += food.calories
			actual_fat += food.fat
			actual_carbs += food.carbs
			actual_protein += food.protein


	abs_fat = actual_fat - (account.ideal_fat/100.0)*(account.ideal_calories * days)
	abs_prot = actual_protein - (account.ideal_protein/100.0)*(account.ideal_calories * days)
	abs_carbs = actual_carbs - (account.ideal_carbs/100.0)*(account.ideal_calories * days)

	actual_offset = (abs(abs_fat) + abs(abs_carbs) + abs(abs_prot))

	# Return Value
	offset_pct = actual_offset / ideal_calories * 100

	for expense in expenses:
		total_expenses += expense.amount
	
	# Return Value
	calories_to_dollars = float(actual_calories) / float(total_expenses)
	
	for exercise in exercises:
		total_burned += exercise.calories_burned

	off_target = (actual_calories - total_burned) - (account.ideal_calories * days)
	off_target_day = off_target / days
	
	# Return Values
	off_target_week = (off_target_day * 7 / 3500.0) + current_weight
	off_target_weeks = (off_target_day * 14 / 3500.0) + current_weight
	off_target_month = (off_target_day * 30 / 3500.0) + current_weight

	return calories_to_dollars, offset_pct, off_target_week, off_target_weeks, off_target_month




def calories_dollars(foods, expenses, days):
	actual_calories = total_expenses = 0.0
	for food in foods:
		actual_servings = food.servings
		if actual_servings > 1:
			actual_calories += food.calories * food.servings
		else:
			actual_calories += food.calories

	for expense in expenses:
		total_expenses += expense.amount

	calories_to_dollars = float(actual_calories) / float(total_expenses)
	return calories_to_dollars

def offset_pct(account, foods, days):
	actual_fat = actual_carbs = actual_protein = actual_servings = 0.0

	for food in foods:
		actual_servings = food.servings
		if actual_servings > 1:
			actual_fat += food.fat * food.servings
			actual_carbs += food.carbs * food.servings
			actual_protein += food.protein * food.servings
		else:
			actual_fat += food.fat
			actual_carbs += food.carbs
			actual_protein += food.protein


	abs_fat = float(actual_fat) - (account.ideal_fat/100.0)*(account.ideal_calories * days)
	abs_prot = actual_protein - (account.ideal_protein/100.0)*(account.ideal_calories * days)
	abs_carbs = actual_carbs - (account.ideal_carbs/100.0)*(account.ideal_calories * days)

	actual_offset = (abs(abs_fat) + abs(abs_carbs) + abs(abs_prot))

	# Return Value
	offset_pct = actual_offset / account.ideal_calories * 100

	return offset_pct

def caloric_deficit(account, foods, exercises, days):
	actual_calories = total_burned = 0.0

	for food in foods:
		actual_servings = food.servings
		if actual_servings > 1:
			actual_calories += food.calories * food.servings
		else:
			actual_calories += food.calories

	for exercise in exercises:
		total_burned += exercise.calories_burned

	off_target = (actual_calories - total_burned) - (account.ideal_calories * days)
	off_target_day = off_target / days
	
	# Return Values
	off_target_week = (off_target_day * 7 / 3500.0) + account.current_weight
	off_target_weeks = (off_target_day * 14 / 3500.0) + account.current_weight
	off_target_month = (off_target_day * 30 / 3500.0) + account.current_weight

	return off_target_week, off_target_weeks, off_target_month

@login_required
def report_list(request):
	print(request.user)
	profile = Profile.objects.get(user=request.user)
	
	calories_to_dollars = offset = off_week = off_weeks = off_month = False
	if request.method == 'POST':
		# date = 'Blah'
		startdate = request.POST.get('startdate')
		enddate = request.POST.get('enddate')
		print('startdate and Endate\n',startdate, enddate)
		if not startdate and not enddate:
			enddate = datetime.datetime.today().strftime('%Y-%m-%d')
			startdate = (datetime.datetime.today() - datetime.timedelta(days=7)).strftime('%Y-%m-%d')
		print('startdate and Endate\n',startdate,enddate)

			
		foods = Food.objects.filter(user=request.user, create_date__range=[startdate,enddate])
		expenses = Expense.objects.filter(user=request.user, create_date__range=[startdate,enddate])
		exercises = Exercise.objects.filter(user=request.user, create_date__range=[startdate,enddate])
		
		datetime_startdate = datetime.datetime.strptime(startdate, "%Y-%m-%d")
		datetime_enddate = datetime.datetime.strptime(enddate, "%Y-%m-%d")
		date_range = datetime_enddate - datetime_startdate
		date_range = int(date_range.days) + 1
		

		if foods and expenses:
			calories_to_dollars = calories_dollars(foods, expenses, date_range)
		if foods:
			offset = offset_pct(profile, foods, date_range)
		if foods and exercises:
			off_week = caloric_deficit(profile, foods, exercises, date_range)[0]
			off_weeks = caloric_deficit(profile, foods, exercises, date_range)[1]
			off_month = caloric_deficit(profile, foods, exercises, date_range)[2]

		context = {'foods':foods,
					'expenses':expenses,
					'exercises':exercises,
					'calories_to_dollars':calories_to_dollars,
					'offset':offset,
					'off_week':off_week,
					'off_weeks':off_weeks,
					'off_month':off_month,
					'test_val':'test_val',
					}

		return render(request,'reports/reports.html', context)

	else:
		default = True
		days = 7
		startdate = datetime.datetime.now() - datetime.timedelta(days=days)	
		enddate = datetime.datetime.now()

		date_range = datetime.timedelta(days=days)
		date_range = date_range.days

		foods = Food.objects.filter(user=request.user, create_date__range=[startdate,enddate])
		expenses = Expense.objects.filter(user=request.user, create_date__range=[startdate,enddate])
		exercises = Exercise.objects.filter(user=request.user, create_date__range=[startdate,enddate])

		if foods and expenses:
			calories_to_dollars = calories_dollars(foods, expenses, date_range)
		if foods:
			offset = offset_pct(profile, foods, date_range)
		if foods and exercises:
			off_week = caloric_deficit(profile, foods, exercises, date_range)[0]
			off_weeks = caloric_deficit(profile, foods, exercises, date_range)[1]
			off_month = caloric_deficit(profile, foods, exercises, date_range)[2]
		
		return render(request,'reports/reports.html', {'foods':foods,
														'expenses':expenses,
														'exercises':exercises,
														'calories_to_dollars':calories_to_dollars,
														'offset':offset,
														'default':default,
														'off_week':off_week,
														'off_weeks':off_weeks,
														'off_month':off_month})

class IndexTemplateView(LoginRequiredMixin, ListView):
	template_name='reports/reports.html'
	context_object_name = 'all_items'
	today = datetime.datetime.today().strftime('%Y-%m-%d')
	seven_days_ago = (datetime.datetime.today() - datetime.timedelta(days=7)).strftime('%Y-%m-%d')

	def get_queryset(self):
		user = self.request.user
		queryset = User.objects.filter(username=user)
		return queryset

	def get_context_data(self, **kwargs):
		context = super(IndexTemplateView, self).get_context_data(**kwargs)
		context['foods'] = Food.objects.filter(user=self.request.user, create_date__range=[seven_days_ago,today])
		context['expenses'] = Expense.objects.filter(user=self.request.user, create_date__range=[seven_days_ago,today])
		context['exercises'] = Exercise.objects.filter(user=self.request.user, create_date__range=[seven_days_ago,today])
		return context

reports/templates/reports/create.html
{% extends 'base.html' %}
{% block content %}
<section id='create_log_entry'>
	<h1>Create a new entry</h1>

	<form method="POST">
		{% csrf_token %}
		<div class='entry'>
			<h3>Expense Log</h3>
			{{expense_form.as_p}}
		</div>
		<div class='entry'>
			<h3>Food Log</h3>
			{{food_form.as_p}}
		</div>
		<div class='entry'>
			<h3>Exercise Log</h3>
			{{exercise_form.as_p}}
		</div>
		<input class='btn_btn_submit' type="submit" value="Create!">
	</form>

</section>
{% endblock %}

reports/templates/reports/reports.html
{% extends 'base.html' %}
{% block content %}
<section id='reports'>
	<h1 class='sectionTitle'>Reports</h1>
		<div class='report_date p-4'>
			<form method='POST' action="{% url 'reports:index' %}">
				{% csrf_token %}
				<input type="date" name="startdate">
				<input type="date" name="enddate">
				<input class='btn btn-primary btn-sm' type="submit" value="Submit">
			</form>
			{% if default %}
				<p>Default is the last 7 Days</p>
			{% endif %}
		</div>

		{% if nodata%}
			<p>Sorry but there is no information for the selected time range.  Please select another date range</p>

		{% else %}
		<div class='report_summary'>
			
			{% if calories_to_dollars %}
				<p>Your getting {{calories_to_dollars|floatformat:2}} calories per dollar spent!</p>
			{% else %}
				<p>Go ahead and put in a few Entries into both Expenses and Foods.  You can find out how many calories you're getting per amount spent</p>
			{% endif %}
			{% if offset %}
				<p>Your within {{offset|floatformat:0}}% of your Goal!</p>
			{% else %}
				<p>Once you have a few Food Entries in, you can start to see how your meals track against your Personal Goals.  The Lower the Percentage the Closer you are to Eating on Target</p>
			{% endif %}
			{% if off_week %}
				<p>If you keep this up you could be at:</p>
				<p>{{off_week|floatformat:2}} lbs in 7 days</p>
				<p>{{off_weeks|floatformat:2}} lbs in 2 weeks</p>
				<p>{{off_month|floatformat:2}} lbs in 1 Month</p>
			{% else %}
				<p>I know you're working out!  But don't you want to know where you could be if you kept it up?  Track it and see</p>
			{% endif %}				
		</div>

		<div class='reports_foods'>
			
			<div id='food_list'>
				<div class='food_header'>
					<h1 class='sectionTitle'>Foods</h1>
					<a class='btn btn-block btn-success' href="{% url 'foods:food_create' %}">Create a Food</a>
				</div>
				{% if foods %}
				<div class='food_table mt-4'>
					<table class='table table-dark table-striped'>
						<thead>
							<tr>
								<td>Log Date</td>
								<td>Item</td>
								<td>Calories</td>
								<td>Servings</td>
								<td>Carbs</td>
								<td>Protein</td>
								<td>Fat</td>
							</tr>
						</thead>
						<tbody>
						{% for food in foods %}
							<tr>
								<td><a href="{% url 'foods:food_detail' pk=food.pk%}">{{food.create_date}}</a></td>
								<td><a href="{% url 'foods:food_detail' pk=food.pk%}">{{food.food_item}}</a></td>
								<td><a href="{% url 'foods:food_detail' pk=food.pk%}">{{food.calories}}</a></td>
								<td><a href="{% url 'foods:food_detail' pk=food.pk%}">{{food.servings}}</a></td>
								<td><a href="{% url 'foods:food_detail' pk=food.pk%}">{{food.carbs}}</a></td>
								<td><a href="{% url 'foods:food_detail' pk=food.pk%}">{{food.protein}}</a></td>
								<td><a href="{% url 'foods:food_detail' pk=food.pk%}">{{food.fat}}</a></td>
								<td><a class='btn btn-info btn-sm' href="{% url 'foods:food_update' pk=food.pk%}">Update</a></td>
								<td><a class='btn btn-primary btn-sm' href="{% url 'foods:food_delete' pk=food.pk%}">Delete</a></td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			{% endif %}
		</div>
		<div class='reports_expenses'>
			<div id='expense_list'>
				<div class='expense_header'>
					<h1 class='sectionTitle'>Expenses</h1>
					<a class='btn btn-block btn-success' href="{% url 'expenses:expense_create' %}">Create an Expense</a>
				</div>
				{% if expenses %}
				<div class='expense_table mt-4'>
					<table class='table table-dark table-striped'>
						<thead>
							<tr>
								<td>Log Date</td>
								<td>Item</td>
								<td>Category</td>
								<td>Amount</td>
								<td></td>
								<td></td>
							</tr>
						</thead>
						<tbody>
						{% for expense in expenses %}
							<tr>
								<td><a href="{% url 'expenses:expense_detail' pk=expense.pk%}">{{expense.create_date}}</a></td>
								<td><a href="{% url 'expenses:expense_detail' pk=expense.pk%}">{{expense.expense_item}}</a></td>
								<td><a href="{% url 'expenses:expense_detail' pk=expense.pk%}">{{expense.expense_type}}</a></td>
								<td><a href="{% url 'expenses:expense_detail' pk=expense.pk%}">{{expense.amount}}</a></td>
								<td><a class='btn btn-info btn-sm' href="{% url 'expenses:expense_update' pk=expense.pk %}">Update</a></td>
								<td><a class='btn btn-primary btn-sm' href="{% url 'expenses:expense_delete' pk=expense.pk %}">Delete</a></td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			{% endif %}
		</div>

		<div class='reports_exercises'>
			<div id='exercise_list'>
				<div class='exercise_header'>
					<h1 class='sectionTitle'>Exercises</h1>
					<a class='btn btn-block btn-success' href="{% url 'exercises:exercise_create' %}">Create an Exercise</a>
				</div>
				{% if exercises %}
				<div class='exercise_table mt-4'>
					<table class='table table-dark table-striped'>
						<thead>
							<tr>
								<td>Log Date</td>
								<td>Exercise Type</td>
								<td>Calories</td>
								<td>Minutes</td>
								<td></td>
								<td></td>
							</tr>
						</thead>
						<tbody>
						{% for exercise in exercises %}
							<tr>
								<td><a href="{% url 'exercises:exercise_detail' pk=exercise.pk%}">{{exercise.create_date}}</a></td>
								<td><a href="{% url 'exercises:exercise_detail' pk=exercise.pk%}">{{exercise.exercise_type}}</a></td>
								<td><a href="{% url 'exercises:exercise_detail' pk=exercise.pk%}">{{exercise.calories_burned}}</a></td>
								<td><a href="{% url 'exercises:exercise_detail' pk=exercise.pk%}">{{exercise.minutes}}</a></td>
								<td><a class='btn btn-info btn-sm' href="{% url 'exercises:exercise_update' pk=exercise.pk%}">Update</a></td>
								<td><a class='btn btn-primary btn-sm' href="{% url 'exercises:exercise_delete' pk=exercise.pk%}">Delete</a></td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			{% endif %}	
		</div>
	{% endif %}
</section>
{% endblock %}