albums/api/urls.py
from django.conf.urls import url
from albums.api import views
app_name = 'api_albums'
urlpatterns = [
	url(r'^$', views.album_list, name = 'api_album_list'),
	url(r'(?P<pk>\d+)',views.album_detail,name='api_album_detail'),
]

books/api/urls.py
from django.conf.urls import url
from books.api import views
app_name = 'api_books'
urlpatterns = [
	url(r'^$', views.book_list, name = 'api_book_list'),
	url(r'(?P<pk>\d+)',views.book_detail,name='api_book_detail'),

]

booksproject/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.contrib import admin
from booksproject import views, settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

# from accounts.forms import CustomAuthForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.IndexTemplateView.as_view(), name ='index'),

    # Book and Albums
    path('books/',include('books.urls', namespace='books')),
    path('api_books/',include('books.api.urls', namespace = 'api_books')),
    path('albums/',include('albums.urls', namespace='albums')),
    path('api_albums/',include('albums.api.urls', namespace = 'api_albums')),
    
    # TAGR App
    path('tagr/',include('tagr.urls', namespace='tagr')),
    
    path('profile/',include('profile.urls', namespace='profile')),

    # path('contact/', views.contactform, name='contactform'),
    path('about_contact/', views.about_contact, name='about_contact'),
    path('thankyou/', views.ThankYou.as_view(), name='thankyou'),
    
    path('apiinfo/', views.APIInfoTemplateView.as_view(), name='apiinfo'),

    # Foods Apps
    path('foods/', include('foods.urls',namespace = 'foods')),
    path('expenses/', include('expenses.urls',namespace = 'expenses')),
    path('exercises/', include('exercises.urls',namespace = 'exercises')),
    path('reports/', include('reports.urls',namespace = 'reports')),

    # path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=CustomAuthForm, redirect_authenticated_user=True), name = 'user_login'),
    # path('logout/', auth_views.LogoutView.as_view(), name = 'user_logout'),
    
    # path('change-password/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('user_logout')), name='password_change'),
    # path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z](1, 13)-[0-9A-Za-z](1, 20))/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from profile import views
from django.contrib.auth import views as auth_views
# from django.core.urlresolvers import reverse_lazy
from django.urls import reverse_lazy
from profile.forms import CustomAuthForm

app_name='profile'

urlpatterns=[
	path('',views.ProfileListView.as_view(), name = 'index'),
	re_path('invite_trainer/(?P<pk>\d+)',views.invite_trainer, name = 'invite_trainer'),
	# re_path(r'^signup/$',views.signup, name = 'signup'),

	re_path('detail/(?P<pk>\d+)',views.ProfileDetailView.as_view(), name = 'profile_detail'),
	# path('create/',views.ProfileCreateView.as_view(), name = 'profile_create'),
	re_path('update/(?P<pk>\d+)/',views.ProfileUpdateView.as_view(), name = 'profile_update'),
	re_path('delete/(?P<pk>\d+)/',views.ProfileDeleteView.as_view(), name = 'profile_delete'),	
]

tagr/urls.py
from django.conf.urls import url
from tagr import views


app_name='tagr'

urlpatterns=[
	url(r'^$',views.IndexTemplateView.as_view(), name = 'index'),
	url(r'^questions/$',views.PostListView.as_view(), name = 'post_list'),
	url(r'^(?P<chapter>\d+)/(?P<pk>\d+)/$',views.PostDetailView.as_view(), name = 'post_detail'),
	url(r'^update/(?P<chapter>\d+)/(?P<pk>\d+)/$',views.PostUpdateView.as_view(), name = 'post_update'),
]

templates/about_contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h1 class='sectionTitle'>About</h1>
<div class='grid-2'>
	<!-- Youtube BootCamp -->
	<div class='m-3'>
		<a href="https://www.youtube.com/playlist?list=PLO3nmckjmjn1nhYcDHD583aqJNqhkKMFQ" target='_blank'><span><i class="fab fa-youtube fa-4x text-success"></i></span>
		<p class='m-3'>Django Full Stack Developer Bootcamp</p></a>
	</div>
	<!-- LinkedIn -->
	<div class='m-3'>
		<a href="https://www.linkedin.com/in/sunilmodi"><span><i class="fab fa-linkedin fa-4x text-primary"></i></span>
		<p class='m-3'>LinkedIn</p></a>
	</div>
	<!-- Youtube wifiNow -->
	<div class='m-3'>
		<a href="https://www.youtube.com/watch?v=piPkvcLwIjI"><span><i class="fab fa-youtube fa-4x text-info"></i></span>
		<p class='m-3'>Presentation</p></a>
	</div>
	<!-- Amazon Books -->
	<div class='m-3'>
		<a href="https://www.amazon.com/Vipassana-Experience-detailed-journey-Meditation/dp/1520284462"><span><i class="fas fa-book fa-4x text-warning"></i></span>
		<p class='m-3'>Publications</p></a>
	</div>
	
</div>

<form method="POST" action="{% url 'about_contact' %}">
	{% csrf_token %}
	<div class="form-group">
		<input class='form-control m-2' type="text" name="name" placeholder="What's your name?">
		<input class='form-control m-2' type="email" name="email" placeholder="What's your Email?">
		<textarea class='form-control m-2' name="message" cols="10" rows="3" placeholder="What's on your mind?"></textarea>
		<input type="submit" class='form-control m-2 btn btn-block btn-info'>
	</div>
</form>
{% endblock %}

templates/apiinfo.html
{% extends 'base.html' %}
{% block content %}

<section>
	<h1 class='sectionTitle'>Welcome to the API Section</h1>
	<div class='grid-2'>
		<div>
			<p><strong>Read the full list of Books</strong></p>
			<p class='m-3'><a href="{% url 'api_books:api_book_list' %}" target="_blank">Full List of Books via HTML</a></p>
			<p class='m-3'><a href="{% url 'api_books:api_book_list' %}?format=json " target="_blank">Full List of Books via JSON</a> </p>
		</div>
	
		<div>
			<p><strong>Read the full list of Albums</strong></p>
			<p class='m-3'><a href="{% url 'api_albums:api_album_list' %}" target="_blank">Full List of Albums via HTML</a></p>
			<p class='m-3'><a href="{% url 'api_albums:api_album_list' %}?format=json " target="_blank">Full List of Albums via JSON</a> </p>
		</div>
	</div>
</section>
<section class='mt-4 text-left'>
	<div>
		<h5>Books API Usage</h5>
		<table class="table table-striped">
			<thead>
				<th>Usage</th>
				<th>Command</th>
			</thead>
			<tbody>
				<tr>
					<td>/GET Browser UI</td>
					<td>api_books/</td>
				</tr>
				<tr>
					<td>/GET Browser JSON</td>
					<td>api_books/?format=json</td>
				</tr>
				<tr>
					<td>/GET Detail Browser UI</td>
					<td>api_books/detail/1</td>
				</tr>
				<tr>
					<td>/GET Detail Browser JSON</td>
					<td>api_books/detail/1?format=json</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div>
		<h5>Albums API Usage</h5>
		<table class="table table-striped">
			<thead>
				<th>Usage</th>
				<th>Command</th>
			</thead>
			<tbody>
				<tr>
					<td>/GET Browser UI</td>
					<td>api_albums/</td>
				</tr>
				<tr>
					<td>/GET Browser JSON</td>
					<td>api_albums/?format=json</td>
				</tr>
				<tr>
					<td>/GET Detail Browser UI</td>
					<td>api_albums/detail/1</td>
				</tr>
				<tr>
					<td>/GET Detail Browser JSON</td>
					<td>api_albums/detail/1?format=json</td>
				</tr>
			</tbody>
		</table>
	</div>
</section>



{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="Demo Project">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Document</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js'></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <header>
        	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			  <a class="navbar-brand" href="#">ModiSidoM</a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarNav">
			    <ul class="navbar-nav">
			      <li class="nav-item active">
			        <a class="nav-link" href="{% url 'index' %}">Home</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'books:index' %}">Books</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'albums:index' %}">Albums</a>
			      </li>
			      <li class="nav-item">
			        {% if user.is_authenticated %}
			        <a class="nav-link" href="{% url 'tagr:post_list' %}">Think and Grow Rich</a>
			        {% else %}
			        <a class="nav-link" href="{% url 'tagr:index' %}">Think and Grow Rich</a>
			        {% endif %}
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'reports:index' %}">Tracker Reports</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'about_contact' %}">About/Contact</a>
			      </li>
			      
			      {% if user.is_authenticated %}
				      <li class="nav-item">
				        <a class="nav-link" href="{% url 'profile:profile_detail' pk=user.pk %}">Profile</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
				      </li>
				  {% else %}
				  	  <li class="nav-item">
				        <a class="nav-link" href="{% url 'account_login' %}?/next={% url 'index' %}">Login</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="{% url 'account_signup' %}?/next={% url 'index' %}">SignUp</a>
				      </li>
				   {% endif %}
			    </ul>
			  </div>
			</nav>
        </header>
    	<div>    
	        {% block index %}{% endblock %}
	    </div>
		
		<div id='content' class="container pb-3">
        {% block content %}{% endblock %}
        </div>
        
        <div>
	        {% block aftercontent %}{% endblock %}
        </div>
    

	   	<footer>
	   		<p>Copyright &copy; 2020 ModiSidoM</p>
	   	</footer>
    </body>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
	<script src='{% static "js/main.js" %}'></script>
    <script type="text/javascript">
	$(document).ready(function(){
		$(".dataTable").DataTable({
        	"order": [[ 0, "asc" ]]
    	});
	});
	</script>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block index %}

<div id="showcase">
	<h1 class='showcaseTitle display-4 pt-5 font-weight-bold'>ModiSidom</h1>
	<p class='lead'>Apps to Simplify Life</p>
</div>
<div id='index' class='grid-4 hideOnSmall'>	
	<!-- Books -->
	<a href="{% url 'books:index' %}">
	<div class="boxBooks appSummary">
		<div>
			<h1 class='sectionTitle'>Books</h1>
		</div>
	</div>
	</a>
    <!-- Albums -->
    <a href="{% url 'albums:index' %}">
	<div class="boxAlbums appSummary">
		<div>
			<h1 class='sectionTitle'>Albums</h1>
		</div>
	</div>
	</a>
	<!-- Think and Grow Rich -->
	<a href="{% url 'tagr:index' %}">
	<div class="boxTagr appSummary">
		<div>
			<h1 class='sectionTitle'>Think and Grow Rich</h1>
		</div>
	</div>
	</a>
    <!-- Expenses -->
    <a href="{% url 'reports:index' %}">
    <div class="boxTracker appSummary">
    	<div>
    		<h1 class='sectionTitle'>Expense Tracker</h1>
    	</div>
    </div>
	</a>
</div>
<div id="mainBooks" class='grid-2'>
	<div class='booksText'>
		<h1 class='booksTextTitle font-weight-bold'>Books to Read in a LifeTime</h1>
		<p class='booksTextPara'>From the 10 popular 100 books to read in a lifetime lists, this is the Definitive Guide.<br>Ranking the most frequent appearances of books on all 10 lists this list gives you the hands down most popular books aggregated</p>
	</div>
	<div class='booksImage'>
		<img src="{% static 'img/booksImage.jpg' %}" alt="">
	</div>
</div>
<div id="mainAlbums" class='grid-2'>
	<div>
		<p class='mainAlbumsTextPara'>Trying figure out what you should listen to next?  How about picking from the list of the greatest albums ever created!  From the Beatles to the Rollings Stones and from Adele to ZZ Top, this list has you covered on the most popular albums to ever be created.</p>
	</div>
	<div class='mainAlbumsTextTitle'>
		<h1>Albums to Listen to In a lifetime</h1>
	</div>
</div>
<div id="mainTagr" class='grid-2'>
	<div class='tagrText'>
		<h1 class='tagrTextTitle'>Think and Grow Rich - The Master Class</h1>
		<p class='tagrTextPara'>Read the book, and write down your thoughts.</p>
	</div>
	<div class="tagrImage">
		<img src="{% static 'img/tagrImage2.jpg'%}" alt="">
	</div>
</div>
<div id="mainTracker" class='grid-2'>
	<div>
		<p class='mainTrackerTextPara'>
			We spend money on food and we track our calories to track the quality of our intake?  Shouldn't we be tracking the quality of our output?<br><br>Track how much money you spend on the quality of calories you eat.
		</p>
	</div>
	<div class='mainTrackerTextTitle'>
		<h1 class='font-weight-bold'>Expenses to Calories Tracker</h1>
	</div>
</div>

{% endblock %}

templates/intro.html
{% extends 'tagr/base.html' %}
{% block body_block %}
<section id='tagr'>
	<div class='tagr_container'>
	<h1>Welcome to the Think and Grow Rich Challenge</h1>

	<p>Napoeloen Hill set out on a quest to understand the minds of the most Successful people in America.</p><br>
	<p>Through his journey he discovered some very similar traits in all these people...and has shared them with you</p><br>
	<p>Read the book, answer the questions</p><br>
	<p>All the progress and benefits gained through this exercise are also private and belong to you and you alone</p><br>
	

	
	<h3><a href="{% url 'tagr:post_list' %}">Start/Continue the Challenge</a></h3>
	</div>
</section>

<section id='journalapp'>
	<h1>Take Tracking to whole new level!</h1>
	<h3>With this custom tracker, find out</h3>
	<ul>
		<li>How many calories are you getting for your Money</li>
		<li>Do your expenses line up with your quality Goals</li>
		<li>Where you could be 30 days from now!</li>
	</ul>
	<h3><a href="{% url 'reports:report_list' %}">Get to My Tracker!</a></h3>
</section>

{% endblock %}

templates/loggedin.html
{% extends 'base.html' %}
{% block body_block %}
<h1>Logged In</h1>



{% endblock %}

templates/loggedout.html
{% extends 'base.html' %}
{% block body_block %}

<h1>Logged Out</h1>


{% endblock %}

templates/login.html
{% extends 'accounts/base.html' %}
{% block content %}
<section id='login' class='container w-auto pb-3'>
<h1 class='font-weight-bold pb-2 pt-5'>Login</h1>
<form method="POST">
	{% csrf_token %}
	<p>Next value {{request.GET.next}}</p>
	<input type="hidden" name="next" value="{{ request.GET.next }}" />
	{{form.as_p}}
	<input class='btn btn-block btn-info' type="submit" value="Login">
	<p><a class='text-info' href="{% url 'password_reset' %}">Forgot?</a> Or Don't have an Account...Go ahead and <a href="{% url 'account_signup' %}">SignUp</a></p>
	<p class='forgot'></p>
</form>
<div class='nopass'>
	
</div>
<div class='clr'></div>
</section>
{% endblock %}

templates/signup.html
{% extends 'accounts/base.html' %}
{% block content %}
<div class="container pb-3">
	<h1 class='font-weight-bold pt-5'>Signup</h1>
	<form class='signUpForm' method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input class='btn btn-block btn-info' type="submit" value="Sign Up">
	</form>
</div>

{% endblock %}

templates/thankyou.html
{% extends 'base.html' %}
{% block content %}
<h1 class='sectionTitle'>Thank you</h1>
{% endblock %}